/**
 * List of canonical timezones according to 2019c iana database.
 * DO NOT RELY ON THIS FOR GETTING THE LIST OF CANONICAL TIMEZONES. Use listTimezones helper instead
 * This list is only meant for testing purposes
 */
export const CANONICAL_TIMEZONES = [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Nairobi',
    'Africa/Algiers',
    'Africa/Lagos',
    'Africa/Bissau',
    'Africa/Maputo',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Ceuta',
    'Africa/El_Aaiun',
    'Africa/Johannesburg',
    'Africa/Juba',
    'Africa/Khartoum',
    'Africa/Monrovia',
    'Africa/Ndjamena',
    'Africa/Sao_Tome',
    'Africa/Tripoli',
    'Africa/Tunis',
    'Africa/Windhoek',
    'America/Adak',
    'America/Anchorage',
    'America/Port_of_Spain',
    'America/Araguaina',
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Catamarca',
    'America/Argentina/Cordoba',
    'America/Argentina/Jujuy',
    'America/Argentina/La_Rioja',
    'America/Argentina/Mendoza',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Salta',
    'America/Argentina/San_Juan',
    'America/Argentina/San_Luis',
    'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia',
    'America/Curacao',
    'America/Asuncion',
    'America/Atikokan',
    'America/Bahia_Banderas',
    'America/Bahia',
    'America/Barbados',
    'America/Belem',
    'America/Belize',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Bogota',
    'America/Boise',
    'America/Cambridge_Bay',
    'America/Campo_Grande',
    'America/Cancun',
    'America/Caracas',
    'America/Cayenne',
    'America/Panama',
    'America/Chicago',
    'America/Chihuahua',
    'America/Costa_Rica',
    'America/Creston',
    'America/Cuiaba',
    'America/Danmarkshavn',
    'America/Dawson_Creek',
    'America/Dawson',
    'America/Denver',
    'America/Detroit',
    'America/Edmonton',
    'America/Eirunepe',
    'America/El_Salvador',
    'America/Tijuana',
    'America/Fort_Nelson',
    'America/Fort_Wayne',
    'America/Fortaleza',
    'America/Glace_Bay',
    'America/Godthab',
    'America/Goose_Bay',
    'America/Grand_Turk',
    'America/Guatemala',
    'America/Guayaquil',
    'America/Guyana',
    'America/Halifax',
    'America/Havana',
    'America/Hermosillo',
    'America/Indiana/Knox',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Tell_City',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Inuvik',
    'America/Iqaluit',
    'America/Jamaica',
    'America/Juneau',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/La_Paz',
    'America/Lima',
    'America/Los_Angeles',
    'America/Maceio',
    'America/Managua',
    'America/Manaus',
    'America/Martinique',
    'America/Matamoros',
    'America/Mazatlan',
    'America/Menominee',
    'America/Merida',
    'America/Metlakatla',
    'America/Mexico_City',
    'America/Miquelon',
    'America/Moncton',
    'America/Monterrey',
    'America/Montevideo',
    'America/Toronto',
    'America/Nassau',
    'America/New_York',
    'America/Nipigon',
    'America/Nome',
    'America/Noronha',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Ojinaga',
    'America/Pangnirtung',
    'America/Paramaribo',
    'America/Phoenix',
    'America/Port-au-Prince',
    'America/Rio_Branco',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Punta_Arenas',
    'America/Rainy_River',
    'America/Rankin_Inlet',
    'America/Recife',
    'America/Regina',
    'America/Resolute',
    'America/Santarem',
    'America/Santiago',
    'America/Santo_Domingo',
    'America/Sao_Paulo',
    'America/Scoresbysund',
    'America/Sitka',
    'America/St_Johns',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'America/Thule',
    'America/Thunder_Bay',
    'America/Vancouver',
    'America/Whitehorse',
    'America/Winnipeg',
    'America/Yakutat',
    'America/Yellowknife',
    'Antarctica/Casey',
    'Antarctica/Davis',
    'Antarctica/DumontDUrville',
    'Antarctica/Macquarie',
    'Antarctica/Mawson',
    'Pacific/Auckland',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Antarctica/Syowa',
    'Antarctica/Troll',
    'Antarctica/Vostok',
    'Europe/Oslo',
    'Asia/Riyadh',
    'Asia/Almaty',
    'Asia/Amman',
    'Asia/Anadyr',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Atyrau',
    'Asia/Baghdad',
    'Asia/Qatar',
    'Asia/Baku',
    'Asia/Bangkok',
    'Asia/Barnaul',
    'Asia/Beirut',
    'Asia/Bishkek',
    'Asia/Brunei',
    'Asia/Kolkata',
    'Asia/Chita',
    'Asia/Choibalsan',
    'Asia/Shanghai',
    'Asia/Colombo',
    'Asia/Dhaka',
    'Asia/Damascus',
    'Asia/Dili',
    'Asia/Dubai',
    'Asia/Dushanbe',
    'Asia/Famagusta',
    'Asia/Gaza',
    'Asia/Hebron',
    'Asia/Ho_Chi_Minh',
    'Asia/Hong_Kong',
    'Asia/Hovd',
    'Asia/Irkutsk',
    'Europe/Istanbul',
    'Asia/Jakarta',
    'Asia/Jayapura',
    'Asia/Jerusalem',
    'Asia/Kabul',
    'Asia/Kamchatka',
    'Asia/Karachi',
    'Asia/Urumqi',
    'Asia/Kathmandu',
    'Asia/Khandyga',
    'Asia/Krasnoyarsk',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Macau',
    'Asia/Magadan',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Nicosia',
    'Asia/Novokuznetsk',
    'Asia/Novosibirsk',
    'Asia/Omsk',
    'Asia/Oral',
    'Asia/Pontianak',
    'Asia/Pyongyang',
    'Asia/Qostanay',
    'Asia/Qyzylorda',
    'Asia/Rangoon',
    'Asia/Sakhalin',
    'Asia/Samarkand',
    'Asia/Seoul',
    'Asia/Srednekolymsk',
    'Asia/Taipei',
    'Asia/Tashkent',
    'Asia/Tbilisi',
    'Asia/Tehran',
    'Asia/Thimphu',
    'Asia/Tokyo',
    'Asia/Tomsk',
    'Asia/Ulaanbaatar',
    'Asia/Ust-Nera',
    'Asia/Vladivostok',
    'Asia/Yakutsk',
    'Asia/Yekaterinburg',
    'Asia/Yerevan',
    'Atlantic/Azores',
    'Atlantic/Bermuda',
    'Atlantic/Canary',
    'Atlantic/Cape_Verde',
    'Atlantic/Faroe',
    'Atlantic/Madeira',
    'Atlantic/Reykjavik',
    'Atlantic/South_Georgia',
    'Atlantic/Stanley',
    'Australia/Sydney',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Broken_Hill',
    'Australia/Currie',
    'Australia/Darwin',
    'Australia/Eucla',
    'Australia/Hobart',
    'Australia/Lord_Howe',
    'Australia/Lindeman',
    'Australia/Melbourne',
    'Australia/Perth',
    'CET',
    'Pacific/Easter',
    'CST6CDT',
    'EET',
    'Europe/Dublin',
    'EST',
    'EST5EDT',
    'Etc/GMT-0',
    'Etc/GMT-1',
    'Pacific/Port_Moresby',
    'Etc/GMT-11',
    'Pacific/Tarawa',
    'Etc/GMT-13',
    'Etc/GMT-14',
    'Etc/GMT-2',
    'Etc/GMT-3',
    'Etc/GMT-4',
    'Etc/GMT-5',
    'Etc/GMT-6',
    'Indian/Christmas',
    'Etc/GMT-8',
    'Pacific/Palau',
    'Etc/GMT+1',
    'Etc/GMT+10',
    'Etc/GMT+11',
    'Etc/GMT+12',
    'Etc/GMT+3',
    'Etc/GMT+4',
    'Etc/GMT+5',
    'Etc/GMT+6',
    'Etc/GMT+7',
    'Etc/GMT+8',
    'Etc/GMT+9',
    'Etc/UTC',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Astrakhan',
    'Europe/Athens',
    'Europe/London',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Prague',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Zurich',
    'Europe/Chisinau',
    'Europe/Copenhagen',
    'Europe/Gibraltar',
    'Europe/Helsinki',
    'Europe/Kaliningrad',
    'Europe/Kiev',
    'Europe/Kirov',
    'Europe/Lisbon',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Minsk',
    'Europe/Monaco',
    'Europe/Moscow',
    'Europe/Paris',
    'Europe/Riga',
    'Europe/Rome',
    'Europe/Samara',
    'Europe/Saratov',
    'Europe/Simferopol',
    'Europe/Sofia',
    'Europe/Stockholm',
    'Europe/Tallinn',
    'Europe/Tirane',
    'Europe/Ulyanovsk',
    'Europe/Uzhgorod',
    'Europe/Vienna',
    'Europe/Vilnius',
    'Europe/Volgograd',
    'Europe/Warsaw',
    'Europe/Zaporozhye',
    'HST',
    'Indian/Chagos',
    'Indian/Cocos',
    'Indian/Kerguelen',
    'Indian/Mahe',
    'Indian/Maldives',
    'Indian/Mauritius',
    'Indian/Reunion',
    'Pacific/Kwajalein',
    'MET',
    'MST',
    'MST7MDT',
    'Pacific/Chatham',
    'Pacific/Apia',
    'Pacific/Bougainville',
    'Pacific/Chuuk',
    'Pacific/Efate',
    'Pacific/Enderbury',
    'Pacific/Fakaofo',
    'Pacific/Fiji',
    'Pacific/Galapagos',
    'Pacific/Gambier',
    'Pacific/Guadalcanal',
    'Pacific/Guam',
    'Pacific/Honolulu',
    'Pacific/Kiritimati',
    'Pacific/Kosrae',
    'Pacific/Majuro',
    'Pacific/Marquesas',
    'Pacific/Pago_Pago',
    'Pacific/Nauru',
    'Pacific/Niue',
    'Pacific/Norfolk',
    'Pacific/Noumea',
    'Pacific/Pitcairn',
    'Pacific/Pohnpei',
    'Pacific/Rarotonga',
    'Pacific/Tahiti',
    'Pacific/Tongatapu',
    'PST8PDT',
    'WET'
];

/*
 * The list of timezones supported by FE is given by the function listTimezones(),
 * which returns the timezones in the 2019c iana database. That database is backward-compatible
 * (the list of timezones keeps changing because humans keep making crazy irrational decisions).
 * The API does not like backward-compatibility though, and they only support some of those
 * timezones (loosely based on https://www.php.net/manual/en/timezones.php). The list of timezones
 * recognized by FE but not supported by BE are the ones that serve as entries for the object below.
 * The value for each entry is the supported timezone we will re-direct to
 */
export const unsupportedTimezoneLinks: { [key: string]: string } = {
    'America/Fort_Wayne': 'America/New_York',
    'Asia/Rangoon': 'Asia/Yangon',
    CET: 'Europe/Paris',
    CST6CDT: 'America/Chicago',
    EET: 'Europe/Istanbul',
    EST: 'America/New_York',
    EST5EDT: 'America/New_York',
    'Etc/GMT+1': 'Atlantic/Cape_Verde',
    'Etc/GMT+10': 'Pacific/Tahiti',
    'Etc/GMT+11': 'Pacific/Niue',
    'Etc/GMT+12': 'Pacific/Niue', // no canonical timezone exists for GMT+12
    'Etc/GMT+2': 'America/Noronha',
    'Etc/GMT+3': 'America/Sao_Paulo',
    'Etc/GMT+4': 'America/Caracas',
    'Etc/GMT+5': 'America/Lima',
    'Etc/GMT+6': 'America/Managua',
    'Etc/GMT+7': 'America/Phoenix',
    'Etc/GMT+8': 'Pacific/Pitcairn',
    'Etc/GMT+9': 'Pacific/Gambier',
    'Etc/GMT-0': 'Europe/London',
    'Etc/GMT-1': 'Europe/Paris',
    'Etc/GMT-10': 'Australia/Brisbane',
    'Etc/GMT-11': 'Australia/Sydney',
    'Etc/GMT-12': 'Pacific/Auckland',
    'Etc/GMT-13': 'Pacific/Fakaofo',
    'Etc/GMT-14': 'Pacific/Kiritimati',
    'Etc/GMT-2': 'Africa/Cairo',
    'Etc/GMT-3': 'Asia/Baghdad',
    'Etc/GMT-4': 'Asia/Dubai',
    'Etc/GMT-5': 'Asia/Tashkent',
    'Etc/GMT-6': 'Asia/Dhaka',
    'Etc/GMT-7': 'Asia/Jakarta',
    'Etc/GMT-8': 'Asia/Shanghai',
    'Etc/GMT-9': 'Asia/Tokyo',
    'Etc/UTC': 'Europe/London',
    HST: 'Pacific/Honolulu',
    MET: 'Europe/Paris',
    MST: 'Europe/Paris',
    MST7MDT: 'America/Denver',
    PST8PDT: 'America/Los_Angeles',
    WET: 'Europe/Lisbon'
};

export const OUTLOOK_TIMEZONE_LINKS: { [key: string]: string } = {
    'Dateline Standard Time': 'Pacific/Niue', // no canonical timezone exists for GMT+12
    'Samoa Standard Time': 'Pacific/Midway',
    'Hawaiian Standard Time': 'Pacific/Honolulu',
    'Alaskan Standard Time': 'America/Anchorage',
    'Pacific Standard Time': 'America/Los_Angeles',
    'Mountain Standard Time': 'America/Denver',
    'Mexico Standard Time 2': 'America/La_Paz',
    'U.S. Mountain Standard Time': 'America/Phoenix',
    'Central Standard Time': 'America/Mexico_City',
    'Canada Central Standard Time': 'America/Regina',
    'Mexico Standard Time': 'America/Mexico_City',
    'Central America Standard Time': 'America/Mexico_City',
    'Eastern Standard Time': 'America/New_York',
    'U.S. Eastern Standard Time': 'America/New_York',
    'S.A. Pacific Standard Time': 'America/Bogota',
    'Atlantic Standard Time': 'America/Halifax',
    'S.A. Western Standard Time': 'America/La_Paz',
    'Pacific S.A. Standard Time': 'America/Santiago',
    'Newfoundland and Labrador Standard Time': 'America/St_Johns',
    'E. South America Standard Time': 'America/Sao_Paulo',
    'S.A. Eastern Standard Time': 'America/Sao_Paulo',
    'Greenland Standard Time': 'America/Godthab',
    'Mid-Atlantic Standard Time': 'Atlantic/Cape_Verde',
    'Azores Standard Time': 'Atlantic/Azores',
    'Cape Verde Standard Time': 'Atlantic/Cape_Verde',
    'GMT Standard Time': 'UTC',
    'Greenwich Standard Time': 'Atlantic/Reykjavik',
    'Central Europe Standard Time': 'Europe/Budapest',
    'Central European Standard Time': 'Europe/Warsaw',
    'Romance Standard Time': 'Europe/Paris',
    'W. Europe Standard Time': 'Europe/Berlin',
    'W. Central Africa Standard Time': 'Africa/Algiers',
    'E. Europe Standard Time': 'Europe/Minsk',
    'Egypt Standard Time': 'Africa/Cairo',
    'FLE Standard Time': 'Europe/Helsinki',
    'GTB Standard Time': 'Europe/Athens',
    'Israel Standard Time': 'Asia/Jerusalem',
    'South Africa Standard Time': 'Africa/Harare',
    'Russian Standard Time': 'Europe/Moscow',
    'Arab Standard Time': 'Asia/Kuwait',
    'E. Africa Standard Time': 'Africa/Nairobi',
    'Arabic Standard Time': 'Asia/Baghdad',
    'Iran Standard Time': 'Asia/Tehran',
    'Arabian Standard Time': 'Asia/Muscat',
    'Caucasus Standard Time': 'Asia/Baku',
    'Transitional Islamic State of Afghanistan Standard Time': 'Asia/Kabul',
    'Ekaterinburg Standard Time': 'Asia/Yekaterinburg',
    'West Asia Standard Time': 'Asia/Tashkent',
    'India Standard Time': 'Asia/Kolkata',
    'Nepal Standard Time': 'Asia/Kathmandu',
    'Central Asia Standard Time': 'Asia/Dhaka',
    'Sri Lanka Standard Time': 'Asia/Colombo',
    'N. Central Asia Standard Time': 'Asia/Novosibirsk',
    'Myanmar Standard Time': 'Asia/Yangon',
    'S.E. Asia Standard Time': 'Asia/Bangkok',
    'North Asia Standard Time': 'Asia/Krasnoyarsk',
    'China Standard Time': 'Asia/Hong_Kong',
    'Singapore Standard Time': 'Asia/Singapore',
    'Taipei Standard Time': 'Asia/Taipei',
    'W. Australia Standard Time': 'Australia/Perth',
    'North Asia East Standard Time': 'Asia/Irkutsk',
    'Korea Standard Time': 'Asia/Seoul',
    'Tokyo Standard Time': 'Asia/Tokyo',
    'Yakutsk Standard Time': 'Asia/Yakutsk',
    'A.U.S. Central Standard Time': 'Australia/Darwin',
    'Cen. Australia Standard Time': 'Australia/Adelaide',
    'A.U.S. Eastern Standard Time': 'Australia/Melbourne',
    'E. Australia Standard Time': 'Australia/Brisbane',
    'Tasmania Standard Time': 'Australia/Hobart',
    'Vladivostok Standard Time': 'Asia/Vladivostok',
    'West Pacific Standard Time': 'Pacific/Guam',
    'Central Pacific Standard Time': 'Asia/Magadan',
    'Fiji Islands Standard Time': 'Pacific/Fiji',
    'New Zealand Standard Time': 'Pacific/Auckland',
    'Tonga Standard Time': 'Pacific/Tongatapu',
    'Azerbaijan Standard Time': 'Asia/Baku',
    'Middle East Standard Time': 'Asia/Beirut',
    'Jordan Standard Time': 'Asia/Amman',
    'Central Standard Time (Mexico)': 'America/Mexico_City',
    'Mountain Standard Time (Mexico)': 'America/La_Paz',
    'Pacific Standard Time (Mexico)': 'America/Tijuana',
    'Namibia Standard Time': 'Africa/Windhoek',
    'Georgian Standard Time': 'Asia/Tbilisi',
    'Central Brazilian Standard Time': 'America/Manaus',
    'Montevideo Standard Time': 'America/Montevideo',
    'Armenian Standard Time': 'Asia/Yerevan',
    'Venezuela Standard Time': 'America/Caracas',
    'Argentina Standard Time': 'America/Argentina/Buenos_Aires',
    'Morocco Standard Time': 'Africa/Casablanca',
    'Pakistan Standard Time': 'Asia/Karachi',
    'Mauritius Standard Time': 'Indian/Mauritius',
    'Paraguay Standard Time': 'America/Asuncion',
    'Kamchatka Standard Time': 'Asia/Kamchatka'
};
